version: '3.6'
services:
  postgres:
    container_name: postgresql_database
    image: postgres:13.8
    restart: unless-stopped
    environment:
      POSTGRES_USER: defaultuser
      POSTGRES_DB: documents
      POSTGRES_PASSWORD: defaultpassword
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - .postgres/:/docker-entrypoint-initdb.d/

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"

volumes:
  postgres-data:
